import express from 'express';
import cors from 'cors';
import {readFileSync,writeFileSync,existsSync,mkdirSync} from 'fs';
import {join,dirname} from 'path';
import {fileURLToPath} from 'url';
import dotenv from 'dotenv';
dotenv.config();
const __dirname=dirname(fileURLToPath(import.meta.url));
const app=express();
const PORT=process.env.PORT||4000;
app.use(cors());
app.use(express.json({limit:'15mb'}));
const DD=join(__dirname,'data');
if(!existsSync(DD))mkdirSync(DD,{recursive:true});
function ld(k){const f=join(DD,k+'.json');try{return existsSync(f)?JSON.parse(readFileSync(f,'utf-8')):null}catch{return null}}
function sv(k,d){writeFileSync(join(DD,k+'.json'),JSON.stringify(d))}
['transactions','inventory','sales','invoices','pricing-config','pricing-recipes'].forEach(k=>{if(!ld(k))sv(k,k.endsWith('config')?{}:[])});
['transactions','inventory','sales','invoices','pricing-config','pricing-recipes'].forEach(k=>{
app.get('/api/data/'+k,(q,r)=>r.json(ld(k)||(k.endsWith('config')?{}:[])));
app.put('/api/data/'+k,(q,r)=>{sv(k,q.body);r.json({ok:true})});
});
const gid=()=>Date.now().toString(36)+Math.random().toString(36).substr(2,5);
app.post('/api/sell',(req,res)=>{const{items,payment='PIX'}=req.body;if(!items?.length)return res.status(400).json({error:'Informe itens'});const inv=ld('inventory')||[],sales=ld('sales')||[],tx=ld('transactions')||[];const results=[];let tot=0;const now=new Date().toISOString().split('T')[0];for(const item of items){const s=(item.name||'').toLowerCase();const p=inv.find(i=>i.name.toLowerCase().includes(s)||s.includes(i.name.toLowerCase().substring(0,6)));if(!p){results.push({name:item.name,error:'Nao encontrado'});continue}if(!p.isRecipe&&p.qty<(item.qty||1)){results.push({name:p.name,error:'Estoque insuficiente'});continue}const qty=item.qty||1,total=p.price*qty,profit=total-p.cost*qty;sales.push({id:gid(),productId:p.id,product:p.name,qty,unitPrice:p.price,discount:0,total,profit,cost:p.cost*qty,payment,customer:'',date:now});tx.push({id:gid(),type:'entrada',description:'Venda: '+p.name+' (x'+qty+')',amount:total,category:'Venda',date:now,payment,notes:'via WhatsApp'});if(!p.isRecipe){const idx=inv.findIndex(i=>i.id===p.id);if(idx>=0)inv[idx].qty-=qty}tot+=total;results.push({name:p.name,qty,price:p.price,total,profit})}sv('inventory',inv);sv('sales',sales);sv('transactions',tx);const ds=sales.filter(s=>s.date===now);res.json({ok:true,items:results,totalSale:tot,payment,dayTotal:ds.reduce((s,t)=>s+t.total,0),dayProfit:ds.reduce((s,t)=>s+t.profit,0),daySalesCount:ds.length})});
app.get('/api/stock',(req,res)=>{const inv=ld('inventory')||[],q=(req.query.q||'').toLowerCase();let items=q?inv.filter(i=>i.name.toLowerCase().includes(q)):inv;res.json({items,lowStock:items.filter(i=>!i.isRecipe&&i.qty<10),total:items.length})});
app.get('/api/summary',(req,res)=>{const date=req.query.date||new Date().toISOString().split('T')[0];const sales=ld('sales')||[],tx=ld('transactions')||[],inv=ld('inventory')||[];const ds=sales.filter(s=>s.date===date),dt=tx.filter(t=>t.date===date);const ent=dt.filter(t=>t.type==='entrada').reduce((s,t)=>s+t.amount,0);const sai=dt.filter(t=>t.type==='saida').reduce((s,t)=>s+t.amount,0);const pc={};ds.forEach(s=>{pc[s.product]=(pc[s.product]||0)+s.qty});res.json({date,salesCount:ds.length,salesTotal:ds.reduce((s,t)=>s+t.total,0),profit:ds.reduce((s,t)=>s+t.profit,0),entradas:ent,saidas:sai,saldo:ent-sai,topProducts:Object.entries(pc).sort((a,b)=>b[1]-a[1]).slice(0,5).map(([name,qty])=>({name,qty})),lowStock:inv.filter(i=>!i.isRecipe&&i.qty<10).map(i=>({name:i.name,qty:i.qty}))})});
app.post('/api/expense',(req,res)=>{const{description,amount,category='Operacional',payment='PIX'}=req.body;if(!description||!amount)return res.status(400).json({error:'Informe descricao e valor'});const tx=ld('transactions')||[];tx.push({id:gid(),type:'saida',description,amount:parseFloat(amount),category,date:new Date().toISOString().split('T')[0],payment,notes:'via WhatsApp'});sv('transactions',tx);res.json({ok:true,description,amount:parseFloat(amount),category})});
app.post('/api/analyze-invoice',async(req,res)=>{const ak=process.env.ANTHROPIC_API_KEY;if(!ak)return res.status(500).json({error:{message:'API Key ausente'}});const{contentBlock}=req.body;if(!contentBlock)return res.status(400).json({error:{message:'Sem arquivo'}});try{const r=await fetch('https://api.anthropic.com/v1/messages',{method:'POST',headers:{'Content-Type':'application/json','x-api-key':ak,'anthropic-version':'2023-06-01'},body:JSON.stringify({model:'claude-sonnet-4-20250514',max_tokens:4000,messages:[{role:'user',content:[contentBlock,{type:'text',text:'Analise esta NF. Responda JSON: {supplier,date,invoice_number,items:[{name,purchase_qty,purchase_unit,units_per_package,unit_cost_per_package}],total}'}]}]})});const d=await r.json();if(d.error)return res.json({error:d.error});res.json({text:(d.content||[]).map(c=>c.text||'').join('')})}catch(err){res.status(500).json({error:{message:err.message}})}});
const AP='Voce e o assistente do FAROL CAFE. Interprete mensagens e responda APENAS JSON: {"action":"sell|stock|summary|expense|help|unknown","data":{},"reply":"texto"}. sell: items:[{name,qty}],payment. stock: query. expense: description,amount,category. Se nao especificar pagamento use PIX.';
app.post('/api/whatsapp/webhook',async(req,res)=>{const{message,from}=req.body;const text=message?.conversation||message?.extendedTextMessage?.text||message?.text||'';const sender=from||message?.key?.remoteJid||'';if(!text?.trim())return res.json({ok:false});console.log('[WA] '+sender+': '+text);const ak=process.env.ANTHROPIC_API_KEY;if(!ak||ak==='COLE_SUA_CHAVE_AQUI')return res.json({reply:'Sistema nao configurado'});try{const ar=await fetch('https://api.anthropic.com/v1/messages',{method:'POST',headers:{'Content-Type':'application/json','x-api-key':ak,'anthropic-version':'2023-06-01'},body:JSON.stringify({model:'claude-sonnet-4-20250514',max_tokens:1000,system:AP,messages:[{role:'user',content:text}]})});const ad=await ar.json();const cl=(ad.content||[]).map(c=>c.text||'').join('').trim();let p;try{p=JSON.parse(cl)}catch{return res.json({reply:'Erro ao processar'})}let reply=p.reply||'';if(p.action==='sell'&&p.data?.items?.length){const r=await fetch('http://localhost:'+PORT+'/api/sell',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(p.data)}).then(r=>r.json());if(r.ok)reply='Venda registrada!\n'+r.items.map(i=>i.error?i.name+': '+i.error:i.qty+'x '+i.name+' R$'+i.total.toFixed(2)).join('\n')+'\nTotal: R$'+r.totalSale.toFixed(2)+' ('+r.payment+')\nHoje: R$'+r.dayTotal.toFixed(2)}else if(p.action==='stock'){const r=await fetch('http://localhost:'+PORT+'/api/stock?q='+encodeURIComponent(p.data?.query||'')).then(r=>r.json());reply=r.items.length===0?'Nenhum produto':r.items.slice(0,10).map(i=>i.name+': '+(i.isRecipe?'sob demanda':i.qty+'un')+' R$'+(i.price||0).toFixed(2)).join('\n')}else if(p.action==='summary'){const r=await fetch('http://localhost:'+PORT+'/api/summary').then(r=>r.json());reply='Resumo '+r.date+'\nFaturamento: R$'+r.salesTotal.toFixed(2)+'\nLucro: R$'+r.profit.toFixed(2)+'\nVendas: '+r.salesCount}else if(p.action==='expense'&&p.data){const r=await fetch('http://localhost:'+PORT+'/api/expense',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(p.data)}).then(r=>r.json());if(r.ok)reply='Despesa: '+r.description+' R$'+r.amount.toFixed(2)}else if(p.action==='help'){reply='FAROL CAFE\nVenda: vendeu 3 cafes\nEstoque: quanto tem de cafe?\nResumo: como foi o dia?\nDespesa: paguei 350 de luz'}const eu=process.env.EVOLUTION_API_URL,ek=process.env.EVOLUTION_API_KEY,ei=process.env.EVOLUTION_INSTANCE||'farolcafe';if(eu&&ek&&sender){try{await fetch(eu+'/message/sendText/'+ei,{method:'POST',headers:{'Content-Type':'application/json',apikey:ek},body:JSON.stringify({number:sender.replace('@s.whatsapp.net',''),text:reply})})}catch(e){console.error('Evo err:',e.message)}}res.json({reply,action:p.action})}catch(err){console.error('WA err:',err);res.json({reply:'Erro interno'})}});
app.get('/api/health',(q,r)=>r.json({status:'ok',ts:new Date().toISOString()}));
app.get('/',(q,r)=>r.send('<html><body style="background:#0e0e1a;color:#e0e0f0;font-family:sans-serif;display:flex;align-items:center;justify-content:center;height:100vh;margin:0"><div style="text-align:center"><h1>FAROL CAFE</h1><p>API rodando</p><p><a href="/api/health" style="color:#00c896">/api/health</a></p></div></body></html>'));
app.listen(PORT,'0.0.0.0',()=>console.log('Farol Cafe porta '+PORT));
